version: '1'

services:
  postgres:
    container_name: "postgres_db"
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_data: