version: '1'
networks:
  dockerNetwork:
name: "fullstack-docker"

services:
  postgres:
    container_name: "postgres_db"
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - dockerNetwork

  backend:
    container_name: "server-nest"
    build:
      context: ./server
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - dockerNetwork

  frontend:
    container_name: "client-react"
    build:
      context: ./client
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - dockerNetwork


volumes:
  postgres_data: